# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76029f3f0ff6b0f5d63a4fe5da4214fb9bff63aaa968b80e86bc98183be96256353f7a52fcc84281f9f68373c9b313103add74f6f8f566599ccecfbb33d15bb5

test:
  secret_key_base: acee4526c3be6413eb98259ff7d54c9c187ed92f260de96a5de37e8fdeb038ad78676565b84d7bb06fd73711fce1cdf8c2527d903b97731bd6196674375b2356

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
